```python
dir(keyword)
```

    ['__all__',
     '__builtins__',
     '__cached__',
     '__doc__',
     '__file__',
     '__loader__',
     '__name__',
     '__package__',
     '__spec__',
     'iskeyword',
     'issoftkeyword',
     'kwlist',
     'softkwlist']

```python
num1 = 0.1 * 3
num2 = 0.3
type(num1)
type(num2)
```

    float

```python
\n #줄바꿈
\t #탭
\\ #백슬래시
```

      Input In [7]
        \n
         ^
    SyntaxError: unexpected character after line continuation character

```python
name = '철수'
print(f'안녕, {name}야')
```

    안녕, 철수야

```python
int('3.5') #(5) 오류
```

    ---------------------------------------------------------------------------
    
    ValueError                                Traceback (most recent call last)
    
    Input In [13], in <cell line: 1>()
    ----> 1 int('3.5')
    
    
    ValueError: invalid literal for int() with base 10: '3.5'

```python
n = 5
m = 9
a = ("**n\n")
print(a*m)
```

    *****
    *****
    *****
    *****
    *****
    *****
    *****
    *****
    *****

```python

```

```python

```
